FROM python:3.9
WORKDIR /app
COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r ./requirements.txt

COPY backend/ . 

EXPOSE 8889

CMD ["sh", "-c", "gunicorn -b 0.0.0.0:${PORT:-8889} app:app"]
